# Generated by Django 4.2.23 on 2025-06-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('sleep_schedule', models.CharField(max_length=50)),
                ('cleanliness', models.CharField(max_length=50)),
                ('introvert_extrovert', models.CharField(max_length=50)),
                ('interests', models.TextField()),
                ('is_submitted', models.BooleanField(default=False)),
            ],
        ),
    ]
