# Generated by Django 4.2.23 on 2025-06-30 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_userprofile_created_at_userprofile_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_initiator', to='matcher.userprofile')),
                ('student2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_partner', to='matcher.userprofile')),
            ],
        ),
    ]
