# Generated by Django 4.2.23 on 2025-07-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0003_matchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cleanliness',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
