# Generated by Django 4.2.23 on 2025-07-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0004_alter_userprofile_cleanliness'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.CharField(choices=[('csai', 'BTech CSAI'), ('csds', 'BTech CSDS'), ('dsai', 'BTech DS & Analytics'), ('design', 'Design'), ('psych', 'Psychology'), ('bba', 'BBA')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
