# Generated by Django 4.2.23 on 2025-07-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0008_remove_studentuser_created_at_studentuser_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
