# Generated by Django 4.2.23 on 2025-07-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0009_remove_studentuser_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
